"""Supplier Evidence Core factual contracts and deterministic evaluation."""
from .alternatives import (
    PROV_COMPARABILITY_EVIDENCE_SOURCE_TYPE,
    PROV_COVERAGE_EVIDENCE_SOURCE_TYPE,
    PROV_OPPORTUNITY_EVIDENCE_SOURCE_TYPE,
    PROV_SIGNIFICANT_IMPROVEMENT_EVIDENCE_SOURCE_TYPE,
    SupplierAlternativeComparabilityDetermination,
    SupplierAlternativeOpportunityDetermination,
    SupplierAlternativeSetCoverage,
    SupplierAlternativeSignificantImprovementDetermination,
    supplier_alternative_comparability_ref,
    supplier_alternative_coverage_ref,
    supplier_alternative_opportunity_ref,
    supplier_alternative_purchase_operation_ref,
    supplier_alternative_significant_improvement_ref,
    supplier_evidence_result_ref,
)
from .engine import evaluate_supplier_evidence
from .models import (
    CandidateResolution,
    ExternalSupplierMetric,
    StructuralComparisonRequest,
    StructuralComparisonResult,
    SupplierCandidateEvidence,
    SupplierDataIssueRef,
    SupplierEvidenceInput,
    SupplierEvidenceResult,
    SupplierHistoricalFact,
    SupplierItemRef,
    SupplierObservation,
    SupplierResultIdentity,
    SupplierSignal,
    SUPPLIER_EVIDENCE_METHODOLOGY_VERSION,
)

__all__ = [
    "PROV_COMPARABILITY_EVIDENCE_SOURCE_TYPE",
    "PROV_COVERAGE_EVIDENCE_SOURCE_TYPE",
    "PROV_OPPORTUNITY_EVIDENCE_SOURCE_TYPE",
    "PROV_SIGNIFICANT_IMPROVEMENT_EVIDENCE_SOURCE_TYPE",
    "SupplierAlternativeComparabilityDetermination",
    "SupplierAlternativeOpportunityDetermination",
    "SupplierAlternativeSetCoverage",
    "SupplierAlternativeSignificantImprovementDetermination",
    "CandidateResolution",
    "ExternalSupplierMetric",
    "StructuralComparisonRequest",
    "StructuralComparisonResult",
    "SupplierCandidateEvidence",
    "SupplierDataIssueRef",
    "SupplierEvidenceInput",
    "SupplierEvidenceResult",
    "SupplierHistoricalFact",
    "SupplierItemRef",
    "SupplierObservation",
    "SupplierResultIdentity",
    "SupplierSignal",
    "SUPPLIER_EVIDENCE_METHODOLOGY_VERSION",
    "evaluate_supplier_evidence",
    "supplier_alternative_comparability_ref",
    "supplier_alternative_coverage_ref",
    "supplier_alternative_opportunity_ref",
    "supplier_alternative_purchase_operation_ref",
    "supplier_alternative_significant_improvement_ref",
    "supplier_evidence_result_ref",
]
